chat/urls.py
from django.urls import path
from .views import *


app_name = "chat"

urlpatterns = [
    path("", chatpage, name="chatpage")
]

gestione/urls.py
from django.urls import path
from .views import *

app_name = "gestione"

urlpatterns = [
    path("", gestione_home, name="home"),
    path("listaservizi/", ServizioListView.as_view(),name="listaservizi"),
    path("ricerca/", search, name="cercaservizio"),
    path("ricerca/<str:sstring>/<str:where>/", ServizioRicercaView.as_view(), name="ricerca_risultati"),
    path("prenota/<pk>/", save_the_date, name="prenota"),
    path("appuntamento/<str:pk>/<str:when>/<str:who>", reservation, name="prenota_risultati"),
    path("situazione/", my_situation, name="situazione"),
    path("cancella_appuntamento/<pk>", DeleteAppuntamentoView.as_view(), name="cancella_appuntamento"),
    path("situazione_generale/", StudioSituationView.as_view(), name="situazione_gen"),
    path("crea_servizio/", CreateServizioView.as_view(), name="crea_servizio"),
    path("cancella_servizio/<pk>/", DeleteServizioView.as_view(), name="cancella_servizio"),
    path("modifica_servizio/<pk>", UpdateServizioView.as_view(), name="modifica_servizio"),
    path("ricerca_appuntamento/", search_reservation, name="ricerca_appuntamento"),
    path("ricerca_appuntamento/<str:sstring>/<str:where>/", AppuntamentoRicercaView.as_view(), name="appuntamento_risultati")
    ]

ivonne/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from .views import home, chi_sono, UserCreateView
from .initcmds import *


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^/$|^home", home, name="home"),
    path("chi_sono/", chi_sono, name="chi_sono" ),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("gestione/", include("gestione.urls")),
    path("chat/", include("chat.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#erase_db()
init_db()
#db_from_now_on()

templates/about_me.html
{% extends 'basebs.html' %}
{% load static %}

{% block title %}Chi è Ivonne!{% endblock %}

{% block content %}
    <br>
    <h2 style="color: deeppink">CHI SONO</h2>
    <div class="container pt-3">
        <br>
        <img src="{% static 'img/whoami.jpg' %}" alt="whoami">
        <br>
        <br>
        <p class="h4" style="color: darkslategray; text-align: justify; font-family: Vivaldi">{% lorem %}</p>
    </div><br>


{% endblock %}

{% block footer %}
        <p class="text-center"> <b>Ivonne!</b> - Riva del Garda (Trento), 38066 - viale Roma, 20 - tel. 0464 550885 - email info@ivonnestudio.com - p.iva 01763060223</p>
{% endblock %}

templates/basebs.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
{#   <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>#}
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>

        <div class="container" style="margin-top:5px";></div>

        <div id="logotipo" style="text-align: center";>
            <a href="{% url 'home' %}"><img src="{% static 'img/logotipo.png' %}"></a>
        </div>

        <div class="container" style="margin-top:5px"></div>

        <style>

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            {#width: 200px;#}
            overflow: hidden;
            background-color: #f1f1f1;
            }

        li {
            {#display: inline;#}
            float:left;
        }

        li a {
            display: block;
            color: #666;
            padding: 14px 16px;
            text-align: center;
            text-decoration: none;
            }

            /* Change the link color on hover */
            li a:hover {
            background-color: #FF1493;
            color: white;
            }
            </style>
        {% endblock %}

        {% block header %}{% endblock %}
        {% load crispy_forms_tags %}

    </head>


    <title>{% block title %} {% endblock %}</title>

    <body>


        {% if user.is_authenticated and "ok" in request.GET.login  %}

        <div id="info" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Welcome {{user.username}} </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p> La procedura di login è andata a buon fine </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Chiudi</button>
            </div>
            </div>
        </div>
        </div>
        <script>
        $(document).ready(function(){
            $("#info").modal('show');
        });
        </script>

        {% endif %}


        <nav>

            {% block navbar %}

            <div id="navbar">
            <ul>


                <li>
                <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>

                <li>
                <a class="nav-link" href="{% url 'chi_sono' %}">Chi sono</a>
                </li>

                <li>
                <a class="nav-link" href="{% url 'gestione:listaservizi' %}">Servizi proposti</a>
                </li>

                <li>
                <a class="nav-link" href="{% url 'gestione:cercaservizio' %}"> Ricerchi un servizio </a>
                </li>

                <li>
                <a class="nav-link" href="{% url 'gestione:home' %}">Gestione Appuntamenti</a>
                </li>

                <li>
                <a class="nav-link" href="{% url 'chat:chatpage' %}"> Info Chat</a>
                </li>

                {% if "Creativi" in user.groups.all.0.name %}
                <li style="float:right">
                <a class="nav-link" href="{% url 'gestione:crea_servizio' %}">Crea Servizio</a>
                </li>
                {% endif %}
            </ul>

            </div>
            {% endblock %}
        </nav>

            <center>

            {% block content %}
            <h2>TITLE HEADING</h2>
            <h5>Title description, Dec 7, 2017</h5>
            <div class="fakeimg">Fake Image</div>
                <p>Some text..</p>
                <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
            {% endblock %}
            <br>
            </center>
{#            </div>#}
{#        </div>#}


        <div class="jumbotron text-center" style="margin-bottom:0" style="margin-top: 0">
        {% block footer %}

        {% if user.is_authenticated %}
        <a class="btn btn-info" href="{% url 'logout' %}" role="button">Logout</a>
        {% else %}
        <a class="btn btn-info" href="{% url 'register' %}" role="button">Registrati</a>
        <a class="btn btn-info" href="{% url 'login' %}" role="button">Login</a>
        {% endif %}

        <a class="btn btn-warning" href="/admin/" role="button">Admin Login</a>

        {%  endblock %}
        </div>


    </body>
</html>

templates/home.html
{% extends 'basebs.html' %}

{% load static %}

{% block title %} Ivonne! {% endblock %}

{% block content %} 

{#<h2 style="font-family:'Vladimir Script'" font-size="40">Seriamente, col sorriso</h2>#}
{#<h5></h5>#}
        <div id="Carousel" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#Carousel" data-slide-to="0" class="active"></li>
                <li data-target="#Carousel" data-slide-to="1"></li>
                <li data-target="#Carousel" data-slide-to="2"></li>
            </ol>

        <!-- The slideshow -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static "img/particolare.jpg" %}" alt="firstimg" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{% static "img/treccia.jpg" %}" alt="secondimg" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{% static "img/vetrine.jpg" %}" alt="thirdimg" class="d-block w-100">
                </div>
            </div>

        <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#Carousel" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>

        </div>
{#<p >Prego, accomodatevi!</p>#}

{% endblock %}

templates/user_create.html
{% extends 'basebs.html' %}

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block title %} Creazione Utente {{ form.user_group_name }} {% endblock %} 

{% block content %}
  <h2>Pagina di Registrazione</h2>
  <p>Si prega di compilare i campi necessari</p> 


<form method="post"> {% csrf_token %}

  {{form | crispy}}
  
  <input type="submit" class="btn btn-success" value="Registrazione">
  
  </form>

{% endblock %}

{% block footer %} {% endblock %}