chat/urls.py
from django.urls import path
from .views import *


app_name = "chat"

urlpatterns = [
    path("", chatpage, name="chatpage")
]

gestione/urls.py
from django.urls import path
from .views import *

app_name = "gestione"

urlpatterns = [
    path("", gestione_home, name="home"),
    path("listaservizi/", ServizioListView.as_view(),name="listaservizi"),
    path("ricerca/", search, name="cercaservizio"),
    path("ricerca/<str:sstring>/<str:where>/", ServizioRicercaView.as_view(), name="ricerca_risultati"),
    path("prenota/<pk>/", save_the_date, name="prenota"),
    path("appuntamento/<str:pk>/<str:when>/<str:who>", reservation, name="prenota_risultati"),
    path("situazione/", my_situation, name="situazione"),
    path("cancella_appuntamento/<pk>", DeleteAppuntamentoView.as_view(), name="cancella_appuntamento"),
    path("situazione_generale/", StudioSituationView.as_view(), name="situazione_gen"),
    path("crea_servizio/", CreateServizioView.as_view(), name="crea_servizio"),
    path("cancella_servizio/<pk>/", DeleteServizioView.as_view(), name="cancella_servizio"),
    path("modifica_servizio/<pk>", UpdateServizioView.as_view(), name="modifica_servizio"),
    path("ricerca_appuntamento/", search_reservation, name="ricerca_appuntamento"),
    path("ricerca_appuntamento/<str:sstring>/<str:where>/", AppuntamentoRicercaView.as_view(), name="appuntamento_risultati")
    ]

ivonne/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from .views import home, chi_sono, UserCreateView
from .initcmds import *


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^/$|^home", home, name="home"),
    path("chi_sono/", chi_sono, name="chi_sono" ),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("gestione/", include("gestione.urls")),
    path("chat/", include("chat.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#erase_db()
init_db()
#db_from_now_on()

gestione/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Servizio(models.Model) :
    immagine = models.ImageField(upload_to='uploaded_images', null=True, blank=True)
    video = models.FileField(upload_to='uploaded_videos', null=True, blank=True,
                             validators=[
                                 FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])
    nome = models.CharField(max_length=50)
    minuti = models.IntegerField(default=30)
    testo = models.TextField(max_length=255)

    class Meta :
        verbose_name_plural = "Servizi"

    def __string__(self):
        return str(self.nome)


class Appuntamento(models.Model) :
    data_ora_inizio = models.DateTimeField(default=None, null=True, blank=True)
    data_ora_fine = models.DateTimeField(default=None, null=True, blank=True)
    servizio = models.ForeignKey(Servizio, on_delete=models.CASCADE, related_name="appuntamento")
    cliente = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, default=None,
                                related_name="appuntamenti_fissati")

    class Meta :
        verbose_name_plural = "Appuntamenti"
        # criterio di ordinamento per il modulo next-prev nelle views
        ordering = ['data_ora_inizio']

    #def __string__(self):
    #    return self.name


class Coda(models.Model) :
    data_ora_inizio = models.DateTimeField(default=None, null=True, blank=True)
    data_ora_fine = models.DateTimeField(default=None, null=True, blank=True)
    servizio = models.ForeignKey(Servizio, on_delete=models.CASCADE, related_name="servizio_richiesto")
    cliente = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, default=None,
                                related_name="lista_attesa")

gestione/forms.py
import datetime as dt
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Servizio, User
from django.forms import ModelForm


class SearchForm(forms.Form):
    CHOICE_LIST = [("Nome", "Cerca tra i Servizi"), ("Minuti", "Cerca durata di esecuzione")]
    helper = FormHelper()
    helper.form_id = "search_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit","Cerca"))
    search_string = forms.CharField(label="Cerca", max_length=50,min_length=2,required=True)
    search_where = forms.ChoiceField(label="Dove", required=True, choices=CHOICE_LIST)

class AppuntamentoSearchForm(forms.Form):
    hours = [x for x in range(8, 18)]
    minutes = [0, 30]
    HOUR_CHOICES = [(dt.time(hour=x), '{:02d}'.format(x)) for x in hours]
    MINS_CHOICES = [(dt.time(minute=x), '{:02d}'.format(x)) for x in minutes]
    CHOICE_LIST = [("Data_ora_inizio", "Cerca data"), ("Cliente", "Cerca Cliente")]
    helper = FormHelper()
    helper.form_id = "appuntamento_search_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit", "Cerca"))
    search_string = forms.CharField(label="Username", max_length=50, min_length=2, required=False)
    giorno = forms.DateField(widget=forms.TextInput(attrs={'type' : 'date'}), label='Giorno', required=False)
    ora = forms.ChoiceField(label="Ora", required=False, choices=HOUR_CHOICES)
    mins = forms.ChoiceField(label="Minuti", required=False, choices=MINS_CHOICES)
    search_where = forms.ChoiceField(label="Dove", required=False, choices=CHOICE_LIST)

class BookForm(forms.Form):
    hours = [x for x in range(8,18)]
    minutes = [0,30]
    HOUR_CHOICES = [(dt.time(hour=x), '{:02d}'.format(x)) for x in hours]
    MINS_CHOICES = [(dt.time(minute=x), '{:02d}'.format(x)) for x in minutes]
    helper = FormHelper()
    helper.form_id = "book_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit","Ricerca"))
    giorno = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}), label='Giorno')
    # forzare l'orario di prenotazione ad un range fissato di orari accettati
    ora = forms.ChoiceField(label="Ora", required = True, choices=HOUR_CHOICES)
    mins = forms.ChoiceField(label="Minuti", required = True, choices=MINS_CHOICES)

class CreativeBookForm(BookForm):
    USER_CHOICES = []
    for u in User.objects.all():
        USER_CHOICES.append((u.pk,u.username))

    cliente = forms.ChoiceField(label="Cliente", required=True, choices=USER_CHOICES)

class ServizioForm(ModelForm):
    helper = FormHelper()
    helper.form_id = "service_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit", "Inserisci"))
    class Meta:
        model = Servizio
        fields = ['immagine', 'nome', 'minuti', 'testo']

gestione/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
from datetime import timedelta, time
from next_prev import *
from django.core.mail import *
from braces.views import GroupRequiredMixin


# Create your views here.
def gestione_home(request) :
    return render(request, template_name="gestione/home.html")


class ServizioListView(ListView) :
    titolo = "I Servizi di Ivonne!"
    model = Servizio
    template_name = "gestione/lista_servizi.html"


def search(request) :
    if request.method == "POST" :
        form = SearchForm(request.POST)
        if form.is_valid() :
            sstring = form.cleaned_data.get("search_string")
            where = form.cleaned_data.get("search_where")
            return redirect("gestione:ricerca_risultati", sstring, where)
    else :
        form = SearchForm()
    return render(request, template_name="gestione/ricerca.html", context={"form" : form})


class ServizioRicercaView(ServizioListView) :
    titolo = "La ricerca ha prodotto i seguenti risultati"

    def get_queryset(self) :
        sstring = self.request.resolver_match.kwargs["sstring"]
        where = self.request.resolver_match.kwargs["where"]

        if "Nome" in where :
            qq = self.model.objects.filter(nome__icontains=sstring)
        else :
            qq = self.model.objects.filter(minuti__icontains=sstring)
        return qq

# prende i dati dal BookForm e li ricostruisce opportunamente
# nel form ho messo due campi distinti per data e ora e voglio ricavare
# un unico datetime (con la funzione combine()) da inserire nel model Appuntamento
# con la funzione combine l'oggetto restituito è timezone unaware, occorre dunque specificare tzinfo
def from_form(form) :
    giorno = form.cleaned_data.get("giorno")
    ora = form.cleaned_data.get("ora")
    mins = form.cleaned_data.get("mins")
    if giorno == None:
        when = None
    else:
        o = ora.split(":")
        m = mins.split(":")
        string = o[0] + ":" + m[1]
        orario = time.fromisoformat(string)
        when = datetime.combine(giorno, orario, tzinfo=timezone.get_current_timezone())
    return when

@login_required
def search_reservation(request) :
    if request.user.groups.filter(name='Creativi').exists():
        if request.method == "POST" :
            form = AppuntamentoSearchForm(request.POST)
            if form.is_valid():
                where = form.cleaned_data.get("search_where")
                if where == "Cliente":
                    sstring = form.cleaned_data.get("search_string")
                    if sstring == '':
                        return redirect("gestione:ricerca_appuntamento")
                    #print(sstring)
                else:
                    sstring = from_form(form)
                if sstring == None:
                    return redirect("gestione:ricerca_appuntamento")
                else:
                    return redirect("gestione:appuntamento_risultati", sstring, where)
        else :
            form = AppuntamentoSearchForm()
    else:
        return redirect("gestione:situazione")
    return render(request, template_name="gestione/ricerca_appuntamento.html", context={"form" : form})


@login_required
def save_the_date(request, pk) :
    if request.user.groups.filter(name='Creativi').exists() :
        if request.method == "POST" :
            form = CreativeBookForm(request.POST)
            if form.is_valid() :
                when = from_form(form)
                who = form.cleaned_data.get("cliente")
                return redirect("gestione:prenota_risultati", pk, when, who)
        else :
            form = CreativeBookForm()
    else :
        if request.method == "POST" :
            form = BookForm(request.POST)
            if form.is_valid() :
                when = from_form(form)
                who = None
                return redirect("gestione:prenota_risultati", pk, when, who)
        else :
            form = BookForm()

    return render(request, template_name="gestione/prenota.html", context={"form" : form})


limite_min = timezone.localtime(timezone.now())


# funzione che, dato un datetime, calcola il giorno successivo alle ore 8
# evitando che sia di domenica o lunedì
def next_day_8(date_time) :
    data = date_time.date()
    # se la data è sabato, il giorno successivo è dopo 3 giorni
    if datetime.weekday(data) == 5 :
        next_day = data + timedelta(days=3)
    # se è domenica, il giorno successivo è dopo 2 giorni
    elif datetime.weekday(data) == 6 :
        next_day = data + timedelta(days=2)
    # altrimenti aggiungi un solo giorno
    else :
        next_day = data + timedelta(days=1)
    # costruisci il giorno successivo alle 8 (timezone aware)
    hour = '08:00'
    start_hour = time.fromisoformat(hour)
    tz_next_day = datetime.combine(next_day, start_hour, tzinfo=timezone.get_current_timezone())
    return tz_next_day


# funzione che, per ogni appuntamento, valuta se il tempo a disposizione tra un appuntamento
# e il successivo è sufficiente per il servizio indicato nell'argomento e
# restituisce due date che soddisfino tale requisito
def nuove_date(servizio) :
    max_hour = ('16:30:00')
    aware_max_hour = timezone.make_aware(time.fromisoformat(max_hour))
    new_dates = []
    if Appuntamento.objects.all().count() == 0:
        new_date = timezone.now()
        new_dates.append(new_date)
        new_date2 = new_date + timedelta(minutes=servizio.minuti)
        new_dates.append(new_date2)
    else:
        ordered_db = Appuntamento.objects.all().order_by('data_ora_inizio')
        for i in ordered_db :
            #considera gli appuntamenti futuri
            if i.data_ora_inizio >= limite_min :
                i_time = timezone.make_aware(i.data_ora_fine.time())
                next_item = next_in_order(i)
                # A) se non ci sono appuntamenti successivi da confrontare
                if next_item == None :
                    # e se la data di fine dell'appuntamento precedente eccede l'orario massimo
                    if i_time > aware_max_hour :
                        # la prima data disponibile è l'inizio del giorno successivo
                        new_date = next_day_8(i.data_ora_fine)
                        new_dates.append(new_date)
                        if len(new_dates) == 2 :
                            break
                        else :
                            # proponi la seconda data nel pomeriggio
                            new_date2 = new_date + timedelta(hours=7)
                            new_dates.append(new_date2)
                    else :
                        new_date = i.data_ora_fine
                        new_dates.append(new_date)
                        if len(new_dates) == 2 :
                            break
                        else :
                            new_date2 = next_day_8(new_date)
                            new_dates.append(new_date2)
                # B) se c'è un appuntamento successivo da confrontare
                else :
                    if i_time > aware_max_hour :
                        fine = next_day_8(i.data_ora_fine)
                    else :
                        fine = i.data_ora_fine
                    difference = next_item.data_ora_inizio - fine
                    # converto la differenza in integer per confrontarla con la durata del servizio
                    difference = difference / timedelta(minutes=1)
                    if int(difference) >= servizio.minuti :
                        new_date = fine
                        new_dates.append(new_date)
                    if len(new_dates) == 2 :
                        break
        else:
            i.delete()
    return new_dates


@login_required
def reservation(request, pk, when, who) :
    date_alternative = [None, None]
    s = get_object_or_404(Servizio, pk=pk)
    a = Appuntamento()
    whenOK = datetime.fromisoformat(when)
    # impedire prenotazioni nel passato
    # con limite_min variabile esterna alla funzione (perché riutilizzata altrove)
    # e impedire la prenotazione nei giorni di chiusura (lunedì=0, domenica=6)
    when_weekday = datetime.weekday(whenOK)
    if when_weekday != 0 and when_weekday != 6 :
        if whenOK > limite_min :
            a.data_ora_inizio = whenOK
            a.data_ora_fine = whenOK + timedelta(minutes=s.minuti)
            a.servizio = s
            if who == 'None' :
                a.cliente = request.user
            else :
                a.cliente = User.objects.get(pk=who)

            errore = "NO_ERRORS"
            for i in Appuntamento.objects.all() :
                if (a.data_ora_inizio >= i.data_ora_inizio and a.data_ora_inizio < i.data_ora_fine) or (
                        a.data_ora_fine > i.data_ora_inizio and a.data_ora_fine <= i.data_ora_fine) :
                    errore = "Appuntamento non disponibile, scelga un'altra data/ora"
                    c = Coda()
                    c.data_ora_inizio = a.data_ora_inizio
                    c.data_ora_fine = a.data_ora_fine
                    c.servizio = s
                    c.cliente = a.cliente
                    c.save()
        else :
            errore = "Non è possibile prenotare appuntamenti antecedenti ad ora!"
    else :
        errore = "Domenica e lunedì sono giorni di chiusura!"

    if errore != "NO_ERRORS" :
        date_alternative = nuove_date(s)

    else :

gestione/templates/gestione/appuntamento.html
{% extends 'basebs.html' %}

{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block title %} Appuntamento {% endblock %}

{#{% block header1 %}#}
{#  <h1>{{servizio}}</h1>#}
{#{% endblock %}#}

{% block content %} 

{% if "NO_ERRORS" == errore %}
<div class="alert alert-success" role="alert">
    {% if "Clienti" in user.groups.all.0.name %}
        Appuntamento fissato! <br> Ci vediamo per il servizio {{ servizio.nome }}! <br> Data e ora: {{ appuntamento.data_ora_inizio|date:'d-m-Y H:i' }}!
        <img src="{% static "img/welcome.jpg" %}" class="d-block w-25">
    {% else %}
        Appuntamento fissato! <br>  Servizio: {{ servizio.nome }} Cliente: {{ appuntamento.cliente }} <br> Data e ora: {{ appuntamento.data_ora_inizio|date:'d-m-Y H:i' }}
    {% endif %}
{% else %}
<div class="alert alert-danger" role="alert">
  Prenotazione fallita: {{ errore }} <br> <br>
    {% if "Clienti" in user.groups.all.0.name %}
    <img src="{% static "img/closed_door.jpg" %}" class="d-block w-25">
    {% endif %}
    <br>
  {% for i in alternativa %}
  <a class="btn btn-danger" href="{% url 'gestione:prenota_risultati' servizio.pk i who %}" role="button">PROPOSTA: {{ i|date:'d-m-Y H:i' }}</a>

  {% endfor %}
  <a class="btn btn-info" href="{% url 'gestione:prenota' servizio.pk %}" role="button"> Ricerchi altre date </a>
{% endif %}
</div>


{% endblock %}

gestione/templates/gestione/cancella_appuntamento.html
{% extends 'basebs.html' %}


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block title %} Cancellazione appuntamento {% endblock %}


{% block content %}
    <br>
    <h2>Cancellazione Appuntamento</h2>
    <br>
<form method="post">{% csrf_token %}
    <p>Si è sicuri di voler cancellare l'appuntamento con data e ora "{{ object.data_ora_inizio|date:'d-m-Y H:i' }}"</p>
    <p>per il Servizio {{ object.servizio.nome }}?</p>
    {{ form }}
    <input type="submit" value="Conferma">
</form>

<br>
    <a class="btn btn-success" href="{% url 'gestione:situazione_gen' %}" role="button">Indietro</a>
<br>
{% endblock %}

gestione/templates/gestione/cancella_servizio.html
{% extends 'basebs.html' %}


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block title %} Cancellazione Servizio {% endblock %}


{% block content %}
    <h2>Cancellazione Servizio</h2>
    <br>
<form method="post">{% csrf_token %}
    <p>Si è sicuri di voler cancellare il Servizio "{{ object.nome }}"?</p>
    {{ form }}
    <input type="submit" value="Conferma">
</form>
<br>
    <a class="btn btn-success" href="{% url 'gestione:listaservizi' %}" role="button">Indietro</a>
<br>
{% endblock %}

gestione/templates/gestione/crea_servizio.html
{% extends 'basebs.html' %}

{% block title %} {{view.title}} {% endblock %} 

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block content %}
  <h1> {{view.title}} </h1>


<br>

<div class="d-flex justify-content-center">

  {% crispy form %}

</div>
<br>


<br>

{% endblock %}

gestione/templates/gestione/home.html
{% extends 'basebs.html' %}

{% block title %} Home di Gestione {% endblock %} 

{% block content %}
  <h2>Home di Gestione</h2>
  {% if "Creativi" in user.groups.all.0.name or user.is_staff %}
    <p style="color: deeppink; font-size: x-large"> Hairstylist loggato: {{ user.username }}</p>
  {%  else %}
  <p style="color: deeppink; font-size: x-large"> Salve,
    {% if user.is_authenticated %}
     {{ user.username }}!
    {% else %}
    Utente non registrato!
    {% endif %}
  </p>

<h4>Cosa desidera fare?</h4>
      <br>
      <h4 style="color: deeppink;"> Per fissare un Appuntamento occorre scegliere il Servizio e cliccare su "Appuntamento" </h4>
  {% endif %}

<br>

<div class="list-group">
  <a href="{% url 'gestione:cercaservizio' %}" class="list-group-item list-group-item-info">Cercare un Servizio</a>
  <a href="{% url 'gestione:listaservizi' %}" class="list-group-item list-group-item-info">Visionare l'elenco dei Servizi proposti</a>
  {% if "Clienti" in user.groups.all.0.name %}
  <a href="{% url 'gestione:situazione' %}" class="list-group-item list-group-item-info">Controllare i miei appuntamenti</a>
  {% endif %}
</div>

    <br>

    {% if "Creativi" in user.groups.all.0.name or user.is_staff %}
    <br>
    <a href="{% url 'gestione:situazione_gen' %}" class="list-group-item list-group-item-warning">Situazione Appuntamenti</a>
    <a href="{% url 'gestione:ricerca_appuntamento' %}" class="list-group-item list-group-item-warning">Ricerca Appuntamento</a>
    <br>
{% endif %}


{% endblock %}

gestione/templates/gestione/lista_servizi.html
{% extends 'basebs.html' %}


{% block title %} Lista dei Servizi {% endblock %}


{% block content %}
    <style>
    .btn-primary,
    .btn-primary:hover,
    .btn-primary:active,
    .btn-primary:visited,
    .btn-primary:focus {
    background-color: #FF1493 !important;
    border-color: #FF1493 !important;
    }
    </style>
    <br>
 {% if object_list.count == 0 %}
   <h2> La ricerca non ha prodotto alcun risultato </h2>
{% else %}
<h2> {{ view.titolo }} </h2>
{% endif %}
<br>
<div class="row">
{% for l in object_list %}
<br>
<div class="col-md-4" style="width: 30rem;">
<div class="card mb-2" style="width: 30rem;">
    {% if l.immagine %}
    <img class="card-img-top" src="{{ l.immagine.url }}" alt="Card image cap" style="max-height:160px"><div class="card-body">
    {% endif %}
    <h5 class="card-title">{{ l.nome }}</h5>
    <p class="card-text"> Tempo di esecuzione: {{ l.minuti }} min</p>
    {{ l.testo }}<br><br>
        <div class="btn-group">
        <a href="{% url 'gestione:prenota' l.pk %}" class="btn btn-info" role="button">Appuntamento</a>  <br><br>
        {% if "Creativi" in user.groups.all.0.name %}
        <a href="{% url 'gestione:cancella_servizio' l.pk %}" class="btn btn-warning" role="button">Cancella Servizio</a>
        <a href="{% url 'gestione:modifica_servizio' l.pk %}" class="btn btn-primary" role="button">Modifica Servizio</a>

        {% endif %}
        </div>
    </div>
  </div>
</div>
<br>
{%endfor%}
</div>
<br>

{% endblock %}

gestione/templates/gestione/situazione.html
{% extends 'basebs.html' %}


{% block title %} Situazione di {{user.username}} {% endblock %}

{% block header1 %}
  <h1>Situazione di {{user.username}} </h1>
  <p>Salve,
    {% if user.is_authenticated %}
     {{ user.username }}!
    {% else %}
    Utente non registrato!
    {% endif %}
  </p> 
{% endblock %}

{% block content %} 
{% if "Clienti" in user.groups.all.0.name %}
<h2>Risulta che ha prenotato {{ listappuntamenti.count }} appuntamenti </h2>
{% endif %}
<br>

{% for a in listappuntamenti %}
<br>
<div class="card">
  <div class="card-header">
     Servizio: {{ a.servizio.nome }}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ a.data_ora_inizio|date:'d-m-Y H:i' }}</h5>
    <p class="card-text"> Durata: {{ a.servizio.minuti }}</p>
    
    <a href="{% url 'gestione:cancella_appuntamento' a.pk %}" class="btn btn-danger"> Cancellazione </a>

  </div>
</div>
<br>
{%endfor%}

    <a href="{% url 'gestione:listaservizi' %}" class="btn btn-success"> Nuovo Appuntamento </a>
    {% if "Creativi" in user.groups.all.0.name %}
    <a href="{% url 'gestione:situazione_gen' %}" class="btn btn-success"> Torna a Situazione Appuntamenti </a>
    {% endif %}
<br>

{% endblock %}

gestione/templates/gestione/situazione_generale.html
{% extends 'basebs.html' %}


{% block title %} Situazione Generale {% endblock %}

{% block content %}
    <br>
  <h2>Loggato come {{user.username}} </h2>
  <p>Salve,
     {{ user.username }}!
  </p> 
    <h2>{{ view.titolo }}</h2>


{% if object_list|length == 0 %}
    <h3>Al momento non è stato fissato alcun appuntamento</h3>
 {% elif object_list|length == 1 %}
    <h3></h3>
 {% else %}
    <h3>Al momento sono stati fissati {{ object_list|length }} appuntamenti</h3>
 {% endif %}
    <br>

{% for a in object_list  %}
<br>
<div class="card">
  <div class="card-header">
      Appuntamento di {{a.cliente}} per {{ a.servizio.nome }}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ a.data_ora_inizio|date:'d-m-Y H:i' }}   </h5>
    <p class="card-text"> Durata: {{ a.servizio.minuti }} </p>
    
    <a href="{% url 'gestione:cancella_appuntamento' a.pk %}" class="btn btn-danger"> Cancella Appuntamento </a>
{#    <a href="{% url 'gestione:modifica' a.pk %}" class="btn btn-info"> Modifica Appuntamento </a>#}
  </div>
</div>
<br>
{%endfor%}

<br>

{% endblock %}